### PR TITLE
Add back cover

### PR DESCRIPTION
**Pull request by jendave**
Add code to create a back cover. I added an example in the skel.tex. It is not perfect by any means but it is a start.

### CODE REVIEW

**Comment by jendave** [comment]
Add updated versions of a few fonts. I also contributed these to the solbera github repo. A few fonts were not showing the correct metadata on a Mac.

**Comment by Artefact2** [comment]
Thank you for your work.

    \renewcommand*{\hbBackcoverImage}{assets/samples/backcoverimage}

It seems you forgot to commit this file.

Also, do you have a vectorial source for `backcover.png` ? If not, where does it come from and what kind of license is it under? Credit goes in `assets/CREDITS.tex` and `assets/samples/CREDITS.tex`.

Your `diamond.png` is also redundant, as there is already a vectorial version named `separator`.

**Comment by jendave** [comment]
I have added the backcoverimage file. I added the svg for the back cover graphic. I created the svg so it will be licensed under the "Do What The F*ck You Want To Public License". I removed the diamond.png and fixed the code to use the separator.

**Comment by jendave** [comment]
Anything further I need to do on this? I know the svg is not very good :-) . I am hoping to update it in the future.

**Comment by Artefact2** [comment]
Sorry, just got around to looking at it today.

That svg file is unusable as it is, it is not vectorial at all and looks just as bad as the png version. The text block also seems to overlap a bit on the right image, but maybe that's intentional.

**Comment by jendave** [comment]
Ok. I'll redo the SVG. thanks

**Comment by jendave** [comment]
Replaced old version with cleaned-up version.

**Comment by Artefact2** [comment]
Thank you for your contribution!

**Pull request merged**
